### ISSUE TITLE
Cant load module : Exec format error

### ISSUE THREAD

**Issue by biji** [nix-community/acpi_call#24]
Hi,
after compiling via dkms, i get this error:

```
modprobe -v acpi_call
insmod /lib/modules/6.1.6-200.fc37.x86_64/extra/acpi_call.ko.xz 
modprobe: ERROR: could not insert 'acpi_call': Exec format error
```

dmesg:
`module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000934c211d, val ffffffffc14c2a77`

Thanks

**Comment by teleshoes** [comment]
do you normally use lzma-compressed kernel modules? many systems are not configured that way out of the box. no idea why your dkms is xz-ing the module if not, but i dont actually use dkms.

i just compiled it with KVER=6.1.6-1-siduction-amd64 on x86_64 jic, so there's nothing actually wrong with 6.1.6. you can confirm that the problem is not in acpi_call by manually compiling and inserting it:
`cd acpi_call && make KVER=6.1.6-200.fc37.x86_64 && insmod acpi_call.ko` or whatever.

good luck

**Comment by biji** [comment]
by default dkms compress `.ko` to `.ko.xz` in my distro

compiling without dkms, give different error:
```
make KVER=6.1.6-200.fc37.x86_64 && insmod acpi_call.ko
make -C /lib/modules/6.1.6-200.fc37.x86_64/build M=/usr/src/acpi_call-1.2.2 modules
make[1]: Entering directory '/usr/src/kernels/6.1.6-200.fc37.x86_64'
  CC [M]  /usr/src/acpi_call-1.2.2/acpi_call.o
  MODPOST /usr/src/acpi_call-1.2.2/Module.symvers
  LD [M]  /usr/src/acpi_call-1.2.2/acpi_call.ko
make[1]: Leaving directory '/usr/src/kernels/6.1.6-200.fc37.x86_64'
insmod: ERROR: could not insert module acpi_call.ko: Invalid module format
```

**Comment by biji** [comment]
Sorry, problem solved now.. something wrong with kernel-devel package:

```
dnf reinstall kernel-devel
dkms remove acpi_call/1.2.2
dkms install acpi_call/1.2.2

modprobe acpi_call
```
